export const amenitiesList = [
  '1st Floor Master Suite',
  '24-Hour Door Person',
  'Air Conditioning',
  'Alarm System',
  'Attic',
  'Attic Fan',
  'Automatic Sprinklers',
  'Balcony Deck',
  'Barn',
  'Basement',
  'Basement Finished',
  'Basement Unfinished',
  'Basketball Court',
  'Bathroom on Main Floor',
  'Beach Access',
  'Bidet',
  'Bilyard Room',
  'Boat Dock',
  'Boat House',
  'Boat Storage',
  'Bonus Room',
  'Breakfast Nook',
  'Broadband Available',
  'Built-in BBQ',
  'Built-in Dressing Vanities',
  'Butcher-block Counters',
  'Butler’s Pantry',
  'Cable TV',
  'Carport',
  'Cathedral Ceilings',
  'Ceramic Counters',
  'Chef’s Kitchen',
  'Cigar Room',
  'City',
  'City Lights Views',
  'Community Beach',
  'Community Clubhouse',
  'Community Pool',
  'Conference Room',
  'Conservatory',
  'Consierge',
  'Corner Lot',
  'Country Club',
  'Country Style Kitchen',
  'Courtyard',
  'Covered Patio',
  'Cul-de-sac',
  'Dead-end Street',
  'Deck',
  'Dining Bar',
  'Dock',
  'Dog Wash Tub',
  'Doorman ',
  'Dry Cleaning Service',
  'Dual Pane Windows',
  'Dual Walk-in Closets',
  'Electric Fence',
  'Elevator',
  'Emergency Room',
  'Endless Pool',
  'Energy-efficient Appliances',
  'Extra-wide Doorways',
  'Family Room',
  'Farm-style Sink',
  'Fenced - Partially',
  'Fenced Yard',
  'Finished Attic',
  'Fireplace',
  'Flex Room',
  'Float',
  'Floating Vanities',
  'Formal Dining Room',
  'Frameless Glass Shower',
  'Free Standing Tub',
  'Freeway Access',
  'Fully Fenced',
  'Game Room',
  'Garage',
  'Garage Attached',
  'Garage Detached',
  'Garden LED Lighting',
  'Gated Community',
  'Gazebo',
  'Golf Course',
  'Golf Course Lot',
  'Grab Bars',
  'Granite Countertops',
  'Great Schools',
  'Guest House',
  'Guest Quarters',
  'Gym/Workout Room',
  'Handicap Accessible',
  'Hardwood Floors',
  'Heated Floors',
  'Heated Pool',
  'High Ceilings',
  'High-Rise',
  'High-speed Internet',
  'High-speed Wi-Fi',
  'His/Hers Dressing Room',
  'Hobby Room',
  'Home Theater',
  'Hot Tub',
  'In-Law Quarters',
  'Indoor Basketball Court',
  'Indoor Pool',
  'Indoor Tennis Court',
  'Jetted Tub',
  'Kitchen Island',
  'Kitchenette',
  'Lake Access',
  'Lake View',
  'Large Kitchen',
  'Large Lot',
  'Library',
  'Loft',
  'Low-Rise',
  'Lower Counter Heights',
  'Marble Counters',
  'Massage Room',
  'Master Suite Balcony',
  'Master Suite Sitting Area',
  'Modern Kitchen',
  'Mountain Views',
  'Mudroom',
  'Multi-purpose Room',
  'Near Parks',
  'Near Schools',
  'New Construction',
  'Ocean Views',
  'Office/Den',
  'Open Floor Plan',
  'Outbuilding',
  'Outdoor Fire Pit',
  'Outdoor Kitchen',
  'Oversized Windows',
  'Panic Room',
  'Panoramic Views',
  'Parking',
  'Parking / Garage Included',
  'Pond',
  'Pool',
  'Pool Slide',
  'Private Patio',
  'Programmable Thermostat',
  'Quite & Private',
  'Rain-shower Head',
  'Ramps',
  'Recessed Lighting',
  'Residents Lounge',
  'Roof-top Deck',
  'RV Parking',
  'Sauna',
  'Screened Porch',
  'Single Flush Toilet',
  'Skylights',
  'Smart Home Features',
  'Smoke Detectors',
  'Solar Heat',
  'Solar Panels',
  'Solar Plumbing',
  'Solarium',
  'Spa',
  'Sport Pool',
  'Sports Court',
  'Steam Room',
  'Stone Counters',
  'Storm Windows',
  'Stove Hood',
  'Sunken Trampoline',
  'Sunroom',
  'Surround Sound',
  'Swimming Pool ',
  'Swimming Pool - Indoor',
  'Tankless Water Heater',
  'Tennis Court',
  'Tile Floors',
  'Trash Compactor',
  'Triple Pane Windows',
  'Uncovered Patio',
  'Unfinished Basement',
  'Urinal',
  'Utilities on Main Floor',
  'Utilities on Upper Floor',
  'Valet',
  'Walk-in Closets',
  'Walk-in Shower',
  'Walk-in Tub',
  'Walk-out Basement',
  'Warming Drawers',
  'Water Softener ',
  'Waterfront',
  'Wet Bar',
  'Whole House Vacuum',
  'Whole-house Fan',
  'Window Shutters',
  'Wine Cellar',
  'Wine Refrigerator',
  'Wine Storage',
  'Wine Tasting Room',
  'Wood Counters',
  'Workshop',
  'Workshop Detached',
  'Wrap-around Deck'
]
